COLOR 15, 1
CLS
PRINT
PRINT "         The Titanic's Length was 882.75'. It sank in 12,460' of water,"
PRINT "         in the North Atlantic, off of the S.E. coast of Newfoundland."
PRINT
PRINT "         To put it in perspective, if we can imagine the ship's length"
PRINT "         as 1" + CHR$(34) + ", then from the surface, it would be lying in 14.115" + CHR$(34)
PRINT "         of water."
DO: LOOP WHILE INKEY$ = ""



