DIM B$(1000), D$(1000), FR$(7), Price(1000), Board$(20), Yourstock(1000), Shares(1000),
	Board(20), Banner$(10)

Banner$(1) = "$ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $"
Banner$(2) = "$      WELCOME TO WALL STREET,    $"
Banner$(3) = "$  A STOCK MARKET GAME OF CHANCE. $"
Banner$(4) = "$    PRESS ANY KEY AND START AN   $"
Banner$(5) = "$   EXCITING TRIP INTO THE WORLD  $"
Banner$(6) = "$           OF ECONOMY.           $"
Banner$(7) = "$ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $"

CLS: LOCATE 12, 29: PRINT "STANDBY, LOADING DATA!"
