10:
	PN$ = "FUNNY FARM STOCK MARKET"

	InfoLine$ = "Press SPACEBAR to buy and sell"

	Trailer$ = "          "

	FR$(1) = "1/8"
	FR$(2) = "1/4"
	FR$(3) = "3/8"
	FR$(4) = "1/2"
	FR$(5) = "5/8"
	FR$(6) = "3/4"
	FR$(7) = "7/8"

	LT$ = "I" + STRING$(78, 205) + ";"
	LM$ = ":" + STRING$(78, 32) + ":"
	LMA$ = "L" + STRING$(78, 205) + "9"
	LB$ = "H" + STRING$(78, 205) + "<"
	Blackline$ = STIRNG$(78, 219)
	Blank$ = STRING$(78, 32)
	D = 0
